<?php

return [
    // Feature flag for the global template catalog.
    'enabled' => (bool) env('FEATURE_TEMPLATE_CATALOG_V2', true),

    // Security: only templates declared here are selectable/assignable.
    'include_uncatalogued' => false,

    'templates' => [
        'wayvio' => [
            'theme' => 'Wayvio',
            'label' => 'Wayvio Style',
            'description' => 'Wayvio base design — customisable colours, fonts and buttons.',
            'order' => 1,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => true,
                'gradient'         => true,
                'overlay'          => true,
                'custom_icons'     => true,
                'dynamic_contrast' => true,
            ],
            'variants' => [
                'default' => [
                    'label'   => 'Teal',
                    'css'     => null,
                    'swatches' => ['#0F3D3E', '#14B8A6', '#F3F7F7'],
                ],
            ],
            'default_variant_id' => 'default',
        ],
        'default' => [
            'theme' => 'default',
            'label' => 'Default',
            'description' => 'Core default template with full background controls.',
            'order' => 10,
            'enabled' => false,
            'variants' => [
                'default' => [
                    'label' => 'Default',
                    'css' => null,
                    'swatches' => ['#111827', '#FFFFFF', '#0EA5E9'],
                ],
            ],
        ],
        'paper' => [
            'theme' => 'Paper',
            'label' => 'Paper',
            'description' => 'Paper-texture template with transparent outlined buttons.',
            'order' => 50,
            'enabled' => true,
            'capabilities' => [
                'header' => true,
                'custom_buttons' => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient' => false,
                'overlay' => false,
            ],
            'variants' => [
                'default' => [
                    'label' => 'Bordeaux',
                    'css' => 'variants/bordeaux.css',
                    'swatches' => ['#7A3643', '#FFFFFF'],
                ],
                'teal' => [
                    'label' => 'Teal',
                    'css' => 'variants/teal.css',
                    'swatches' => ['#1E7C76', '#FFFFFF'],
                ],
                'pastel' => [
                    'label' => 'Pastel',
                    'css' => 'variants/pastel.css',
                    'swatches' => ['#F3DCC8', '#000000'],
                ],
                'dark-gray' => [
                    'label' => 'Dark Gray',
                    'css' => 'variants/dark-gray.css',
                    'swatches' => ['#6F7379', '#FFFFFF'],
                ],
                'light-gray' => [
                    'label' => 'Light Gray',
                    'css' => 'variants/light-gray.css',
                    'swatches' => ['#F7F7F3', '#000000'],
                ],
            ],
            'default_variant_id' => 'default',
        ],
        // ── FREE TEMPLATES (v1–v3) — accent & button colour freely customisable ──

        'dunes' => [
            'theme' => 'Dunes',
            'label' => 'Dunes',
            'description' => 'Soft ambient radial gradients on warm off-white.',
            'order' => 100,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#0F3D3E', 'button_style' => 'outline', 'button_text_color' => '#0F3D3E', 'button_background_color' => 'transparent', 'button_border_color' => '#0F3D3E'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F5EEE6', '#0F3D3E', '#C05A2A']],
            ],
            'default_variant_id' => 'default',
        ],
        'edge' => [
            'theme' => 'Edge',
            'label' => 'Edge Light',
            'description' => 'Warm corner glow on a clean cream base.',
            'order' => 110,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#145A32', 'button_style' => 'outline', 'button_text_color' => '#145A32', 'button_background_color' => 'transparent', 'button_border_color' => '#145A32'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F5F3EC', '#145A32', '#B5451B']],
            ],
            'default_variant_id' => 'default',
        ],
        'riso' => [
            'theme' => 'Riso',
            'label' => 'Riso',
            'description' => 'Blurred ink blobs with multiply blend — risograph look.',
            'order' => 120,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#B33000', 'button_style' => 'outline', 'button_text_color' => '#B33000', 'button_background_color' => 'transparent', 'button_border_color' => '#B33000'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F5EEE4', '#B33000', '#224488']],
            ],
            'default_variant_id' => 'default',
        ],
        'dots' => [
            'theme' => 'Dots',
            'label' => 'Dot Field',
            'description' => 'Dot grid with radial vignette on warm cream.',
            'order' => 130,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#3B3020', 'button_style' => 'outline', 'button_text_color' => '#3B3020', 'button_background_color' => 'transparent', 'button_border_color' => '#3B3020'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0EAE0', '#3B3020', '#8B3000']],
            ],
            'default_variant_id' => 'default',
        ],
        'halftone' => [
            'theme' => 'Halftone',
            'label' => 'Halftone',
            'description' => 'Two overlapping diagonal dot screens — riso print aesthetic.',
            'order' => 140,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#8B3000', 'button_style' => 'outline', 'button_text_color' => '#8B3000', 'button_background_color' => 'transparent', 'button_border_color' => '#8B3000'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0E4D8', '#8B3000', '#1A2A6C']],
            ],
            'default_variant_id' => 'default',
        ],
        'linen' => [
            'theme' => 'Linen',
            'label' => 'Linen',
            'description' => 'Crossed thread gradients on warm off-white.',
            'order' => 150,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#5C3D1E', 'button_style' => 'outline', 'button_text_color' => '#5C3D1E', 'button_background_color' => 'transparent', 'button_border_color' => '#5C3D1E'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F2EDE4', '#5C3D1E', '#2B5016']],
            ],
            'default_variant_id' => 'default',
        ],
        'sunburst' => [
            'theme' => 'Sunburst',
            'label' => 'Sunburst',
            'description' => 'Soft conic sun rays in warm amber.',
            'order' => 160,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#8B4500', 'button_style' => 'outline', 'button_text_color' => '#8B4500', 'button_background_color' => 'transparent', 'button_border_color' => '#8B4500'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0E4C8', '#8B4500', '#1A3C6C']],
            ],
            'default_variant_id' => 'default',
        ],
        'topo' => [
            'theme' => 'Topo',
            'label' => 'Topo Lines',
            'description' => 'Topographic contour rings on warm cream.',
            'order' => 170,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#1B3A4B', 'button_style' => 'outline', 'button_text_color' => '#1B3A4B', 'button_background_color' => 'transparent', 'button_border_color' => '#1B3A4B'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F4EFE6', '#1B3A4B', '#7B3F00']],
            ],
            'default_variant_id' => 'default',
        ],
        'cross' => [
            'theme' => 'Cross',
            'label' => 'Crosshatch',
            'description' => 'Layered diagonal hatch lines — hand-drawn print look.',
            'order' => 180,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#3A2A10', 'button_style' => 'outline', 'button_text_color' => '#3A2A10', 'button_background_color' => 'transparent', 'button_border_color' => '#3A2A10'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0EAE0', '#3A2A10', '#0F3D3E']],
            ],
            'default_variant_id' => 'default',
        ],
        'confetti' => [
            'theme' => 'Confetti',
            'label' => 'Confetti',
            'description' => 'Scattered multicolour confetti dots on warm white.',
            'order' => 200,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#8E2A21', 'button_style' => 'outline', 'button_text_color' => '#8E2A21', 'button_background_color' => 'transparent', 'button_border_color' => '#8E2A21'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F5F2E8', '#C0392B', '#2471A3']],
            ],
            'default_variant_id' => 'default',
        ],
        'marble' => [
            'theme' => 'Marble',
            'label' => 'Marble',
            'description' => 'Warm marble with delicate vein lines.',
            'order' => 210,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#2C3E50', 'button_style' => 'outline', 'button_text_color' => '#2C3E50', 'button_background_color' => 'transparent', 'button_border_color' => '#2C3E50'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F5F0E8', '#2C3E50', '#A04020']],
            ],
            'default_variant_id' => 'default',
        ],
        'check' => [
            'theme' => 'Check',
            'label' => 'Big Check',
            'description' => 'Bold oversized checkerboard in maroon and cream.',
            'order' => 230,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#F0E8D8', 'button_style' => 'outline', 'button_text_color' => '#F0E8D8', 'button_background_color' => 'transparent', 'button_border_color' => '#F0E8D8'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#6B2020', '#F0E8D8', '#FFFFFF']],
            ],
            'default_variant_id' => 'default',
        ],
        'cloud' => [
            'theme' => 'Cloud',
            'label' => 'Pastel Cloud',
            'description' => 'Dreamy sky gradient with painted cloud forms.',
            'order' => 240,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#1A3A6C', 'button_style' => 'outline', 'button_text_color' => '#1A3A6C', 'button_background_color' => 'transparent', 'button_border_color' => '#1A3A6C'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#C8D8F0', '#1A3A6C', '#C05A20']],
            ],
            'default_variant_id' => 'default',
        ],
        'wabi-paper' => [
            'theme' => 'Wabi-Paper',
            'label' => 'Wabi Paper',
            'description' => 'Warm handmade paper texture with subtle fibers.',
            'order' => 250,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => true,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => true,
            ],
            'design_defaults' => ['text_accent_color' => '#4A3520', 'button_style' => 'outline', 'button_text_color' => '#4A3520', 'button_background_color' => 'transparent', 'button_border_color' => '#4A3520'],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#EDE8DC', '#4A3520', '#0F3D3E']],
            ],
            'default_variant_id' => 'default',
        ],

        // ── LOCKED TEMPLATES — fully curated look, colours & fonts fixed ──

        'ink' => [
            'theme' => 'Ink',
            'label' => 'Ink Wash',
            'description' => 'Deep indigo wash with layered dark gradients.',
            'order' => 260,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#181226', '#E8DFC8']],
            ],
            'default_variant_id' => 'default',
        ],
        'aurora-field' => [
            'theme' => 'Aurora-Field',
            'label' => 'Aurora',
            'description' => 'Northern lights smears on a deep dark base.',
            'order' => 270,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#0E0C1C', '#F1E8D8']],
            ],
            'default_variant_id' => 'default',
        ],
        'bauhaus' => [
            'theme' => 'Bauhaus',
            'label' => 'Bauhaus',
            'description' => 'Geometric collage of primary shapes on cream.',
            'order' => 290,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#EEE8DC', '#14130F']],
            ],
            'default_variant_id' => 'default',
        ],
        'glass' => [
            'theme' => 'Glass',
            'label' => 'Stained Glass',
            'description' => 'Vivid conic wedges with dark leading lines.',
            'order' => 300,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#2A1840', '#F3EFE7']],
            ],
            'default_variant_id' => 'default',
        ],
        'memphis' => [
            'theme' => 'Memphis',
            'label' => 'Memphis',
            'description' => '80s Memphis shapes — dots, blob, triangle, zigzag.',
            'order' => 320,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0EBE0', '#14130F']],
            ],
            'default_variant_id' => 'default',
        ],
        'blueprint' => [
            'theme' => 'Blueprint',
            'label' => 'Blueprint',
            'description' => 'Technical grid on deep indigo — engineering blueprint.',
            'order' => 340,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#1A1830', '#BFE0F5']],
            ],
            'default_variant_id' => 'default',
        ],
        'chrome' => [
            'theme' => 'Chrome',
            'label' => 'Chrome',
            'description' => 'Iridescent metallic conic — Y2K chrome finish.',
            'order' => 360,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#606070', '#FFFFFF']],
            ],
            'default_variant_id' => 'default',
        ],
        'lava' => [
            'theme' => 'Lava',
            'label' => 'Lava Lamp',
            'description' => 'Hot blurred blobs over deep magenta — lava lamp effect.',
            'order' => 370,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#1E0A18', '#FFE3D2']],
            ],
            'default_variant_id' => 'default',
        ],
        'brush' => [
            'theme' => 'Brush',
            'label' => 'Brushstroke',
            'description' => 'Painterly diagonal brush slashes on warm cream.',
            'order' => 380,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#F0E8DC', '#3A0E0A']],
            ],
            'default_variant_id' => 'default',
        ],
        'matisse' => [
            'theme' => 'Matisse',
            'label' => 'Matisse',
            'description' => 'Organic cutout shapes on warm yellow-ochre.',
            'order' => 400,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#EDE4D0', '#14130F']],
            ],
            'default_variant_id' => 'default',
        ],
        'plasma' => [
            'theme' => 'Plasma',
            'label' => 'Plasma',
            'description' => 'Vivid four-corner mesh gradient — psychedelic energy.',
            'order' => 410,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#8020A0', '#FFFFFF']],
            ],
            'default_variant_id' => 'default',
        ],
        'acid' => [
            'theme' => 'Acid',
            'label' => 'Acid',
            'description' => 'Psychedelic hard-light blobs on acid yellow-green.',
            'order' => 430,
            'enabled' => true,
            'capabilities' => [
                'header'           => true,
                'custom_buttons'   => false,
                'background_image' => false,
                'solid_background' => false,
                'gradient'         => false,
                'overlay'          => false,
                'dynamic_contrast' => false,
            ],
            'variants' => [
                'default' => ['label' => 'Default', 'css' => null, 'swatches' => ['#6A9010', '#14130F']],
            ],
            'default_variant_id' => 'default',
        ],
    ],
];
